# Docker Requirements
install.packages("devtools")
# devtools::install_version(package = "aws.s3", version = "0.3.21")
# devtools::install_version(package = "aws.signature", version = "0.6.0")
devtools::install_version(package = "dashboardthemes", version = "1.1.3")
devtools::install_version(package = "data.table", version = "1.13.2")
devtools::install_version(package = "dplyr", version = "1.0.2")
devtools::install_version(package = "DT", version = "0.16")
devtools::install_version(package = "fst", version = "0.9.4")
devtools::install_version(package = "ggdark", version = "0.2.1")
devtools::install_version(package = "ggplot2", version = "3.3.3")
devtools::install_version(package = "htmltools", version = "0.5.1.1")
devtools::install_version(package = "lubridate", version = "1.7.9.2")
devtools::install_version(package = "plotly", version = "4.9.3")
devtools::install_version(package = "reshape2", version = "1.4.4")
devtools::install_version(package = "scales", version = "1.1.1")
devtools::install_version(package = "shiny", version = "1.5.0")
devtools::install_version(package = "shinycssloaders", version = "1.0.0")
devtools::install_version(package = "shinydashboard", version = "0.7.1")
devtools::install_version(package = "shinyWidgets", version = "0.6.0")
devtools::install_version(package = "stringr", version = "1.4.0")
devtools::install_version(package = "tidyr", version = "1.1.2")
devtools::install_version(package = "viridis", version = "0.5.1")
devtools::install_version(package = "viridisLite", version = "0.3.0")
devtools::install_version(package = "gridExtra", version = "2.3")
install.packages("googleCloudStorageR")
devtools::install_local(path = "/tmp/eddycopipe_0.2.2.tar.gz")